layout_spectrum: 0.5382984719918764
typography_spectrum: 0.7498954069239115
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 1
  lightness: 0.030484564214815744
  saturation: 0.25536116322567043
  rhythmicContrast: 0.8058775246304709
coverPrefs:
  filter: false
name: 'Star Light Travel Egypt '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e9b52dbc-39e3-44e9-b0a3-20543952e088.jpg
analytics:
  facebook: ''
  google: UA-80814309-3
  twitter: ''
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/1b1b1ad2-afd4-4bd4-8b42-ca94b3ed9d44.jpg
purpose:
  - type: contact
    label: 'Call us:01117614828'
    url: 'tel:01117614828'
  - type: contact
    label: 'Email us:'
    url: 'mailto:info@starlighteg.com'
title: Star Light Travel
description: the premium quality of traveling
author: {}
content_rating:
  adult: false
navigation:
  - name: 'Hotels & Resorts:'
    id: c7a64780-2715-40dd-89ee-3ad92359b925
    type: content
  - name: 'Tour Packages:'
    id: d58d7143-b361-4f6f-bfdd-aa74d609b939
    type: content
  - name: 'About us..... '
    id: 5eadd189-3e5d-4228-8b84-00d84945ed79
    type: content
content: []
github: true
